In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

# numpy array

In [3]:
my_list = [10, 20, 30, 40]

In [4]:
type(my_list)

list

In [5]:
np.array(my_list)

array([10, 20, 30, 40])

In [7]:
np_array = np.array(my_list)

In [8]:
type(np_array)

numpy.ndarray

In [9]:
np_array[0]

10

In [10]:
np_array[1]

20

In [11]:
np_array[0] = 100

In [12]:
np_array

array([100,  20,  30,  40])

In [13]:
np_array.max()

100

In [14]:
np_array.min()

20

In [15]:
np_array.mean()

47.5

In [16]:
matrix_list = [[1,0,0],[0,1,0],[0,0,1],[0,0,0]]

In [17]:
type(matrix_list)

list

In [19]:
numpy_matrix_list = np.array(matrix_list)

In [20]:
numpy_matrix_list

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 0]])

In [21]:
numpy_matrix_list[0]

array([1, 0, 0])

In [22]:
numpy_matrix_list[0][0]

1

In [23]:
numpy_matrix_list.shape

(4, 3)

In [24]:
range(0,10)

range(0, 10)

In [26]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [27]:
list(range(0,10,2))

[0, 2, 4, 6, 8]

In [28]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
np.arange(0,30,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [32]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [33]:
np.zeros((9,9))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [34]:
np.ones((9,9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [36]:
np.linspace(0,10,5) #0'dan 10'a kadar eşit aralıklarla 5 adet değer yazdırır.

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [37]:
np.random.randint(1,20,3) #1'den 20'ye kadar 3 tane rastgele integer verir

array([18, 14, 19])

In [38]:
#numpy array methods

In [41]:
my_numpy_list = np.arange(0,20) #0'dan 19 dahil birer birer artarak rakamları verir

In [42]:
my_numpy_list

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [43]:
my_numpy_list[4]

4

In [44]:
my_numpy_list[4:9]

array([4, 5, 6, 7, 8])

In [46]:
my_numpy_list[4:13:3]

array([ 4,  7, 10])

In [47]:
my_list = list(range(0,20))

In [48]:
my_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [49]:
my_list[4:13:3]

[4, 7, 10]

In [51]:
# my_list[4:13:3] = -10 listede bu işleme izin verilmiyor

In [54]:
my_numpy_list[4:19:3] = -100

In [55]:
my_numpy_list

array([   0,    1,    2,    3, -100,    5,    6, -100,    8,    9, -100,
         11,   12, -100,   14,   15, -100,   17,   18,   19])

In [56]:
other_list = np.arange(0,15)

In [57]:
other_list

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [58]:
other_list[4:9]

array([4, 5, 6, 7, 8])

In [59]:
slicing_list = other_list[4:9]

In [60]:
slicing_list

array([4, 5, 6, 7, 8])

In [61]:
slicing_list[0]

4

In [62]:
slicing_list[:] = 100

In [63]:
slicing_list

array([100, 100, 100, 100, 100])

In [64]:
other_list

array([  0,   1,   2,   3, 100, 100, 100, 100, 100,   9,  10,  11,  12,
        13,  14])

In [65]:
numpy_list_3 = np.arange(0,20)

In [66]:
numpy_list_3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [67]:
numpy_list_3_copy = numpy_list_3.copy()

In [68]:
numpy_list_3_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [69]:
slicing_3 = numpy_list_3_copy[4:9]

In [70]:
slicing_3

array([4, 5, 6, 7, 8])

In [71]:
slicing_3[:] = -100

In [72]:
slicing_3

array([-100, -100, -100, -100, -100])

In [73]:
numpy_list_3_copy

array([   0,    1,    2,    3, -100, -100, -100, -100, -100,    9,   10,
         11,   12,   13,   14,   15,   16,   17,   18,   19])

In [74]:
numpy_list_3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [75]:
# array operations

In [76]:
new_array = np.random.randint(1,150,25)

In [77]:
new_array

array([131,  73,  53, 133,  82,  55,  33,  18,  18, 146,  36,  41, 103,
        56,   7, 147,  80,  75,  39,  31,  79,  69,  54, 109,  28])

In [78]:
new_array > 50

array([ True,  True,  True,  True,  True,  True, False, False, False,
        True, False, False,  True,  True, False,  True,  True,  True,
       False, False,  True,  True,  True,  True, False])

In [79]:
result_array = new_array > 50

In [80]:
result_array

array([ True,  True,  True,  True,  True,  True, False, False, False,
        True, False, False,  True,  True, False,  True,  True,  True,
       False, False,  True,  True,  True,  True, False])

In [81]:
new_array

array([131,  73,  53, 133,  82,  55,  33,  18,  18, 146,  36,  41, 103,
        56,   7, 147,  80,  75,  39,  31,  79,  69,  54, 109,  28])

In [82]:
new_array[result_array]

array([131,  73,  53, 133,  82,  55, 146, 103,  56, 147,  80,  75,  79,
        69,  54, 109])

In [83]:
last_array = np.arange(0,30)

In [84]:
last_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [85]:
last_array +last_array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58])

In [86]:
last_array * last_array

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625,
       676, 729, 784, 841])